bsub -o /cluster/scratch/wendlerc/lsfcsss/ -G es_puesch -n 12 -R "rusage[mem=1000, ngpus_excl_p=1]" -R "select[gpu_mtotal0>=10000]" -W 4:00 python project/genotype/regression.py --l1_coef 0  --wandb_project genotype_supervised_random_smallerdata_l1eq0 --use_subset --random --train_fraction 0.10 --wandb_name trained_42 --seed 42 --group trained
bsub -o /cluster/scratch/wendlerc/lsfcsss/ -G es_puesch -n 12 -R "rusage[mem=1000, ngpus_excl_p=1]" -R "select[gpu_mtotal0>=10000]" -W 4:00 python project/genotype/regression.py --l1_coef 0 --freeze --wandb_project genotype_supervised_random_smallerdata_l1eq0 --use_subset --random --train_fraction 0.10 --wandb_name random_42 --seed 42 --group random
bsub -o /cluster/scratch/wendlerc/lsfcsss/ -G es_puesch -n 12 -R "rusage[mem=1000, ngpus_excl_p=1]" -R "select[gpu_mtotal0>=10000]" -W 4:00 python project/genotype/regression.py --l1_coef 0  --wandb_pretrained ridgeslowverybig_with_3augmentations_42 --wandb_project genotype_supervised_random_smallerdata_l1eq0 --use_subset --random --train_fraction 0.10 --wandb_name finetuned_ridgeslowverybig_with_3augmentations_42 --seed 42 --group finetuned_ridgeslowverybig_with_3augmentations
bsub -o /cluster/scratch/wendlerc/lsfcsss/ -G es_puesch -n 12 -R "rusage[mem=1000, ngpus_excl_p=1]" -R "select[gpu_mtotal0>=10000]" -W 4:00 python project/genotype/regression.py --l1_coef 0 --freeze --wandb_pretrained ridgeslowverybig_with_3augmentations_42 --wandb_project genotype_supervised_random_smallerdata_l1eq0 --use_subset --random --train_fraction 0.10 --wandb_name frozen_ridgeslowverybig_with_3augmentations_42 --seed 42 --group frozen_ridgeslowverybig_with_3augmentations
bsub -o /cluster/scratch/wendlerc/lsfcsss/ -G es_puesch -n 12 -R "rusage[mem=1000, ngpus_excl_p=1]" -R "select[gpu_mtotal0>=10000]" -W 4:00 python project/genotype/regression.py --l1_coef 0  --wandb_project genotype_supervised_random_smallerdata_l1eq0 --use_subset --random --train_fraction 0.10 --wandb_name trained_43 --seed 43 --group trained
bsub -o /cluster/scratch/wendlerc/lsfcsss/ -G es_puesch -n 12 -R "rusage[mem=1000, ngpus_excl_p=1]" -R "select[gpu_mtotal0>=10000]" -W 4:00 python project/genotype/regression.py --l1_coef 0 --freeze --wandb_project genotype_supervised_random_smallerdata_l1eq0 --use_subset --random --train_fraction 0.10 --wandb_name random_43 --seed 43 --group random
bsub -o /cluster/scratch/wendlerc/lsfcsss/ -G es_puesch -n 12 -R "rusage[mem=1000, ngpus_excl_p=1]" -R "select[gpu_mtotal0>=10000]" -W 4:00 python project/genotype/regression.py --l1_coef 0  --wandb_pretrained ridgeslowverybig_with_3augmentations_43 --wandb_project genotype_supervised_random_smallerdata_l1eq0 --use_subset --random --train_fraction 0.10 --wandb_name finetuned_ridgeslowverybig_with_3augmentations_43 --seed 43 --group finetuned_ridgeslowverybig_with_3augmentations
bsub -o /cluster/scratch/wendlerc/lsfcsss/ -G es_puesch -n 12 -R "rusage[mem=1000, ngpus_excl_p=1]" -R "select[gpu_mtotal0>=10000]" -W 4:00 python project/genotype/regression.py --l1_coef 0 --freeze --wandb_pretrained ridgeslowverybig_with_3augmentations_43 --wandb_project genotype_supervised_random_smallerdata_l1eq0 --use_subset --random --train_fraction 0.10 --wandb_name frozen_ridgeslowverybig_with_3augmentations_43 --seed 43 --group frozen_ridgeslowverybig_with_3augmentations
bsub -o /cluster/scratch/wendlerc/lsfcsss/ -G es_puesch -n 12 -R "rusage[mem=1000, ngpus_excl_p=1]" -R "select[gpu_mtotal0>=10000]" -W 4:00 python project/genotype/regression.py --l1_coef 0  --wandb_project genotype_supervised_random_smallerdata_l1eq0 --use_subset --random --train_fraction 0.10 --wandb_name trained_44 --seed 44 --group trained
bsub -o /cluster/scratch/wendlerc/lsfcsss/ -G es_puesch -n 12 -R "rusage[mem=1000, ngpus_excl_p=1]" -R "select[gpu_mtotal0>=10000]" -W 4:00 python project/genotype/regression.py --l1_coef 0 --freeze --wandb_project genotype_supervised_random_smallerdata_l1eq0 --use_subset --random --train_fraction 0.10 --wandb_name random_44 --seed 44 --group random
bsub -o /cluster/scratch/wendlerc/lsfcsss/ -G es_puesch -n 12 -R "rusage[mem=1000, ngpus_excl_p=1]" -R "select[gpu_mtotal0>=10000]" -W 4:00 python project/genotype/regression.py --l1_coef 0  --wandb_pretrained ridgeslowverybig_with_3augmentations_44 --wandb_project genotype_supervised_random_smallerdata_l1eq0 --use_subset --random --train_fraction 0.10 --wandb_name finetuned_ridgeslowverybig_with_3augmentations_44 --seed 44 --group finetuned_ridgeslowverybig_with_3augmentations
bsub -o /cluster/scratch/wendlerc/lsfcsss/ -G es_puesch -n 12 -R "rusage[mem=1000, ngpus_excl_p=1]" -R "select[gpu_mtotal0>=10000]" -W 4:00 python project/genotype/regression.py --l1_coef 0 --freeze --wandb_pretrained ridgeslowverybig_with_3augmentations_44 --wandb_project genotype_supervised_random_smallerdata_l1eq0 --use_subset --random --train_fraction 0.10 --wandb_name frozen_ridgeslowverybig_with_3augmentations_44 --seed 44 --group frozen_ridgeslowverybig_with_3augmentations
bsub -o /cluster/scratch/wendlerc/lsfcsss/ -G es_puesch -n 12 -R "rusage[mem=1000, ngpus_excl_p=1]" -R "select[gpu_mtotal0>=10000]" -W 4:00 python project/genotype/regression.py --l1_coef 0  --wandb_project genotype_supervised_random_smallerdata_l1eq0 --use_subset --random --train_fraction 0.10 --wandb_name trained_45 --seed 45 --group trained
bsub -o /cluster/scratch/wendlerc/lsfcsss/ -G es_puesch -n 12 -R "rusage[mem=1000, ngpus_excl_p=1]" -R "select[gpu_mtotal0>=10000]" -W 4:00 python project/genotype/regression.py --l1_coef 0 --freeze --wandb_project genotype_supervised_random_smallerdata_l1eq0 --use_subset --random --train_fraction 0.10 --wandb_name random_45 --seed 45 --group random
bsub -o /cluster/scratch/wendlerc/lsfcsss/ -G es_puesch -n 12 -R "rusage[mem=1000, ngpus_excl_p=1]" -R "select[gpu_mtotal0>=10000]" -W 4:00 python project/genotype/regression.py --l1_coef 0  --wandb_pretrained ridgeslowverybig_with_3augmentations_45 --wandb_project genotype_supervised_random_smallerdata_l1eq0 --use_subset --random --train_fraction 0.10 --wandb_name finetuned_ridgeslowverybig_with_3augmentations_45 --seed 45 --group finetuned_ridgeslowverybig_with_3augmentations
bsub -o /cluster/scratch/wendlerc/lsfcsss/ -G es_puesch -n 12 -R "rusage[mem=1000, ngpus_excl_p=1]" -R "select[gpu_mtotal0>=10000]" -W 4:00 python project/genotype/regression.py --l1_coef 0 --freeze --wandb_pretrained ridgeslowverybig_with_3augmentations_45 --wandb_project genotype_supervised_random_smallerdata_l1eq0 --use_subset --random --train_fraction 0.10 --wandb_name frozen_ridgeslowverybig_with_3augmentations_45 --seed 45 --group frozen_ridgeslowverybig_with_3augmentations
bsub -o /cluster/scratch/wendlerc/lsfcsss/ -G es_puesch -n 12 -R "rusage[mem=1000, ngpus_excl_p=1]" -R "select[gpu_mtotal0>=10000]" -W 4:00 python project/genotype/regression.py --l1_coef 0  --wandb_project genotype_supervised_random_smallerdata_l1eq0 --use_subset --random --train_fraction 0.10 --wandb_name trained_46 --seed 46 --group trained
bsub -o /cluster/scratch/wendlerc/lsfcsss/ -G es_puesch -n 12 -R "rusage[mem=1000, ngpus_excl_p=1]" -R "select[gpu_mtotal0>=10000]" -W 4:00 python project/genotype/regression.py --l1_coef 0 --freeze --wandb_project genotype_supervised_random_smallerdata_l1eq0 --use_subset --random --train_fraction 0.10 --wandb_name random_46 --seed 46 --group random
bsub -o /cluster/scratch/wendlerc/lsfcsss/ -G es_puesch -n 12 -R "rusage[mem=1000, ngpus_excl_p=1]" -R "select[gpu_mtotal0>=10000]" -W 4:00 python project/genotype/regression.py --l1_coef 0  --wandb_pretrained ridgeslowverybig_with_3augmentations_46 --wandb_project genotype_supervised_random_smallerdata_l1eq0 --use_subset --random --train_fraction 0.10 --wandb_name finetuned_ridgeslowverybig_with_3augmentations_46 --seed 46 --group finetuned_ridgeslowverybig_with_3augmentations
bsub -o /cluster/scratch/wendlerc/lsfcsss/ -G es_puesch -n 12 -R "rusage[mem=1000, ngpus_excl_p=1]" -R "select[gpu_mtotal0>=10000]" -W 4:00 python project/genotype/regression.py --l1_coef 0 --freeze --wandb_pretrained ridgeslowverybig_with_3augmentations_46 --wandb_project genotype_supervised_random_smallerdata_l1eq0 --use_subset --random --train_fraction 0.10 --wandb_name frozen_ridgeslowverybig_with_3augmentations_46 --seed 46 --group frozen_ridgeslowverybig_with_3augmentations
bsub -o /cluster/scratch/wendlerc/lsfcsss/ -G es_puesch -n 12 -R "rusage[mem=1000, ngpus_excl_p=1]" -R "select[gpu_mtotal0>=10000]" -W 4:00 python project/genotype/regression.py --l1_coef 0  --wandb_project genotype_supervised_random_smallerdata_l1eq0 --use_subset --random --train_fraction 0.10 --wandb_name trained_47 --seed 47 --group trained
bsub -o /cluster/scratch/wendlerc/lsfcsss/ -G es_puesch -n 12 -R "rusage[mem=1000, ngpus_excl_p=1]" -R "select[gpu_mtotal0>=10000]" -W 4:00 python project/genotype/regression.py --l1_coef 0 --freeze --wandb_project genotype_supervised_random_smallerdata_l1eq0 --use_subset --random --train_fraction 0.10 --wandb_name random_47 --seed 47 --group random
bsub -o /cluster/scratch/wendlerc/lsfcsss/ -G es_puesch -n 12 -R "rusage[mem=1000, ngpus_excl_p=1]" -R "select[gpu_mtotal0>=10000]" -W 4:00 python project/genotype/regression.py --l1_coef 0  --wandb_pretrained ridgeslowverybig_with_3augmentations_47 --wandb_project genotype_supervised_random_smallerdata_l1eq0 --use_subset --random --train_fraction 0.10 --wandb_name finetuned_ridgeslowverybig_with_3augmentations_47 --seed 47 --group finetuned_ridgeslowverybig_with_3augmentations
bsub -o /cluster/scratch/wendlerc/lsfcsss/ -G es_puesch -n 12 -R "rusage[mem=1000, ngpus_excl_p=1]" -R "select[gpu_mtotal0>=10000]" -W 4:00 python project/genotype/regression.py --l1_coef 0 --freeze --wandb_pretrained ridgeslowverybig_with_3augmentations_47 --wandb_project genotype_supervised_random_smallerdata_l1eq0 --use_subset --random --train_fraction 0.10 --wandb_name frozen_ridgeslowverybig_with_3augmentations_47 --seed 47 --group frozen_ridgeslowverybig_with_3augmentations
bsub -o /cluster/scratch/wendlerc/lsfcsss/ -G es_puesch -n 12 -R "rusage[mem=1000, ngpus_excl_p=1]" -R "select[gpu_mtotal0>=10000]" -W 4:00 python project/genotype/regression.py --l1_coef 0  --wandb_project genotype_supervised_random_smallerdata_l1eq0 --use_subset --random --train_fraction 0.10 --wandb_name trained_48 --seed 48 --group trained
bsub -o /cluster/scratch/wendlerc/lsfcsss/ -G es_puesch -n 12 -R "rusage[mem=1000, ngpus_excl_p=1]" -R "select[gpu_mtotal0>=10000]" -W 4:00 python project/genotype/regression.py --l1_coef 0 --freeze --wandb_project genotype_supervised_random_smallerdata_l1eq0 --use_subset --random --train_fraction 0.10 --wandb_name random_48 --seed 48 --group random
bsub -o /cluster/scratch/wendlerc/lsfcsss/ -G es_puesch -n 12 -R "rusage[mem=1000, ngpus_excl_p=1]" -R "select[gpu_mtotal0>=10000]" -W 4:00 python project/genotype/regression.py --l1_coef 0  --wandb_pretrained ridgeslowverybig_with_3augmentations_48 --wandb_project genotype_supervised_random_smallerdata_l1eq0 --use_subset --random --train_fraction 0.10 --wandb_name finetuned_ridgeslowverybig_with_3augmentations_48 --seed 48 --group finetuned_ridgeslowverybig_with_3augmentations
bsub -o /cluster/scratch/wendlerc/lsfcsss/ -G es_puesch -n 12 -R "rusage[mem=1000, ngpus_excl_p=1]" -R "select[gpu_mtotal0>=10000]" -W 4:00 python project/genotype/regression.py --l1_coef 0 --freeze --wandb_pretrained ridgeslowverybig_with_3augmentations_48 --wandb_project genotype_supervised_random_smallerdata_l1eq0 --use_subset --random --train_fraction 0.10 --wandb_name frozen_ridgeslowverybig_with_3augmentations_48 --seed 48 --group frozen_ridgeslowverybig_with_3augmentations
bsub -o /cluster/scratch/wendlerc/lsfcsss/ -G es_puesch -n 12 -R "rusage[mem=1000, ngpus_excl_p=1]" -R "select[gpu_mtotal0>=10000]" -W 4:00 python project/genotype/regression.py --l1_coef 0  --wandb_project genotype_supervised_random_smallerdata_l1eq0 --use_subset --random --train_fraction 0.10 --wandb_name trained_49 --seed 49 --group trained
bsub -o /cluster/scratch/wendlerc/lsfcsss/ -G es_puesch -n 12 -R "rusage[mem=1000, ngpus_excl_p=1]" -R "select[gpu_mtotal0>=10000]" -W 4:00 python project/genotype/regression.py --l1_coef 0 --freeze --wandb_project genotype_supervised_random_smallerdata_l1eq0 --use_subset --random --train_fraction 0.10 --wandb_name random_49 --seed 49 --group random
bsub -o /cluster/scratch/wendlerc/lsfcsss/ -G es_puesch -n 12 -R "rusage[mem=1000, ngpus_excl_p=1]" -R "select[gpu_mtotal0>=10000]" -W 4:00 python project/genotype/regression.py --l1_coef 0  --wandb_pretrained ridgeslowverybig_with_3augmentations_49 --wandb_project genotype_supervised_random_smallerdata_l1eq0 --use_subset --random --train_fraction 0.10 --wandb_name finetuned_ridgeslowverybig_with_3augmentations_49 --seed 49 --group finetuned_ridgeslowverybig_with_3augmentations
bsub -o /cluster/scratch/wendlerc/lsfcsss/ -G es_puesch -n 12 -R "rusage[mem=1000, ngpus_excl_p=1]" -R "select[gpu_mtotal0>=10000]" -W 4:00 python project/genotype/regression.py --l1_coef 0 --freeze --wandb_pretrained ridgeslowverybig_with_3augmentations_49 --wandb_project genotype_supervised_random_smallerdata_l1eq0 --use_subset --random --train_fraction 0.10 --wandb_name frozen_ridgeslowverybig_with_3augmentations_49 --seed 49 --group frozen_ridgeslowverybig_with_3augmentations
bsub -o /cluster/scratch/wendlerc/lsfcsss/ -G es_puesch -n 12 -R "rusage[mem=1000, ngpus_excl_p=1]" -R "select[gpu_mtotal0>=10000]" -W 4:00 python project/genotype/regression.py --l1_coef 0  --wandb_project genotype_supervised_random_smallerdata_l1eq0 --use_subset --random --train_fraction 0.10 --wandb_name trained_50 --seed 50 --group trained
bsub -o /cluster/scratch/wendlerc/lsfcsss/ -G es_puesch -n 12 -R "rusage[mem=1000, ngpus_excl_p=1]" -R "select[gpu_mtotal0>=10000]" -W 4:00 python project/genotype/regression.py --l1_coef 0 --freeze --wandb_project genotype_supervised_random_smallerdata_l1eq0 --use_subset --random --train_fraction 0.10 --wandb_name random_50 --seed 50 --group random
bsub -o /cluster/scratch/wendlerc/lsfcsss/ -G es_puesch -n 12 -R "rusage[mem=1000, ngpus_excl_p=1]" -R "select[gpu_mtotal0>=10000]" -W 4:00 python project/genotype/regression.py --l1_coef 0  --wandb_pretrained ridgeslowverybig_with_3augmentations_50 --wandb_project genotype_supervised_random_smallerdata_l1eq0 --use_subset --random --train_fraction 0.10 --wandb_name finetuned_ridgeslowverybig_with_3augmentations_50 --seed 50 --group finetuned_ridgeslowverybig_with_3augmentations
bsub -o /cluster/scratch/wendlerc/lsfcsss/ -G es_puesch -n 12 -R "rusage[mem=1000, ngpus_excl_p=1]" -R "select[gpu_mtotal0>=10000]" -W 4:00 python project/genotype/regression.py --l1_coef 0 --freeze --wandb_pretrained ridgeslowverybig_with_3augmentations_50 --wandb_project genotype_supervised_random_smallerdata_l1eq0 --use_subset --random --train_fraction 0.10 --wandb_name frozen_ridgeslowverybig_with_3augmentations_50 --seed 50 --group frozen_ridgeslowverybig_with_3augmentations
bsub -o /cluster/scratch/wendlerc/lsfcsss/ -G es_puesch -n 12 -R "rusage[mem=1000, ngpus_excl_p=1]" -R "select[gpu_mtotal0>=10000]" -W 4:00 python project/genotype/regression.py --l1_coef 0  --wandb_project genotype_supervised_random_smallerdata_l1eq0 --use_subset --random --train_fraction 0.10 --wandb_name trained_51 --seed 51 --group trained
bsub -o /cluster/scratch/wendlerc/lsfcsss/ -G es_puesch -n 12 -R "rusage[mem=1000, ngpus_excl_p=1]" -R "select[gpu_mtotal0>=10000]" -W 4:00 python project/genotype/regression.py --l1_coef 0 --freeze --wandb_project genotype_supervised_random_smallerdata_l1eq0 --use_subset --random --train_fraction 0.10 --wandb_name random_51 --seed 51 --group random
bsub -o /cluster/scratch/wendlerc/lsfcsss/ -G es_puesch -n 12 -R "rusage[mem=1000, ngpus_excl_p=1]" -R "select[gpu_mtotal0>=10000]" -W 4:00 python project/genotype/regression.py --l1_coef 0  --wandb_pretrained ridgeslowverybig_with_3augmentations_51 --wandb_project genotype_supervised_random_smallerdata_l1eq0 --use_subset --random --train_fraction 0.10 --wandb_name finetuned_ridgeslowverybig_with_3augmentations_51 --seed 51 --group finetuned_ridgeslowverybig_with_3augmentations
bsub -o /cluster/scratch/wendlerc/lsfcsss/ -G es_puesch -n 12 -R "rusage[mem=1000, ngpus_excl_p=1]" -R "select[gpu_mtotal0>=10000]" -W 4:00 python project/genotype/regression.py --l1_coef 0 --freeze --wandb_pretrained ridgeslowverybig_with_3augmentations_51 --wandb_project genotype_supervised_random_smallerdata_l1eq0 --use_subset --random --train_fraction 0.10 --wandb_name frozen_ridgeslowverybig_with_3augmentations_51 --seed 51 --group frozen_ridgeslowverybig_with_3augmentations
